import {jest} from '@jest/globals';
import {Agent} from '../../src/Agent.js';
import {EmbeddedRelay} from '../helpers/EmbeddedRelay.js';
import {generateSecretKey, getPublicKey} from 'nostr-tools';

// Increase timeout for E2E
jest.setTimeout(30000);

describe.skip('Chatbot E2E Communication', () => {
    let relay;
    let relayUrl;
    let alice;
    let bob;

    beforeAll(async () => {
        relay = new EmbeddedRelay();
        relayUrl = await relay.start();
    });

    afterAll(async () => {
        if (alice) await alice.shutdown();
        if (bob) await bob.shutdown();
        await relay.stop();
    });

    test('Alice and Bob should exchange messages via Nostr', async () => {
        // Setup Keys
        // Using ephemeral keys generated by Agent if not provided, but we want to know pubkeys
        // So we generate them manually here to config

        // nostr-tools v2 generateSecretKey returns Uint8Array, we need hex for config
        // Actually our NostrChannel expects hex string or generates it.
        // Let's rely on internal generation but we need to extract pubkey.
        // Or better, provide them.

        // Simple 32-byte hex for testing
        const aliceKey = "1".repeat(64); // invalid but sufficient for mock if not validated strictly?
        // Real keys preferred.
        const sk1 = generateSecretKey();
        const sk2 = generateSecretKey();
        const aliceHex = Buffer.from(sk1).toString('hex');
        const bobHex = Buffer.from(sk2).toString('hex');
        const alicePub = getPublicKey(sk1);
        const bobPub = getPublicKey(sk2);

        // Init Alice
        alice = new Agent({
            id: 'alice',
            channelConfigPath: null, // manual config
            lm: {provider: 'dummy'}
        });

        // Manual Channel Setup for Alice
        const {NostrChannel} = await import('../../src/io/index.js');
        const aliceChan = new NostrChannel({
            id: 'nostr',
            relays: [relayUrl],
            privateKey: aliceHex,
            // Listen for everything or specifically Bob
            filters: [{kinds: [1], '#p': [alicePub]}]
        });
        alice.channelManager.register(aliceChan);
        await aliceChan.connect();

        // Init Bob
        bob = new Agent({
            id: 'bob',
            lm: {provider: 'dummy'}
        });
        const bobChan = new NostrChannel({
            id: 'nostr',
            relays: [relayUrl],
            privateKey: bobHex,
            filters: [{kinds: [1], '#p': [bobPub]}]
        });
        bob.channelManager.register(bobChan);
        await bobChan.connect();

        // Wait for connection stability
        await new Promise(r => setTimeout(r, 500));

        // Setup Promise to wait for reception
        const aliceReceived = new Promise(resolve => {
            alice.channelManager.on('message', (msg) => {
                if (msg.content.includes('Hello Alice')) resolve(msg);
            });
        });

        const bobReceived = new Promise(resolve => {
            bob.channelManager.on('message', (msg) => {
                if (msg.content.includes('Hello Bob')) {
                    // Bob replies automatically via logic or we simulate reply here
                    // We'll simulate manual reply from Bob's logic side for the test
                    resolve(msg);
                }
            });
        });

        // 1. Alice sends to Bob
        // Using MeTTa primitive simulation or direct JS call
        // Direct JS for reliability in test:
        await alice.channelManager.sendMessage('nostr', bobPub, 'Hello Bob', {kind: 1}); // Public mention/DM logic depends on implementation.
        // NostrChannel sends kind 1 by default unless kind 4 specified.
        // If we want DM, use kind 4. But relay filter above listens for kind 1 with p tag (mention).
        // To send a mention (kind 1 with p tag), we need to handle that in NostrChannel.
        // Current NostrChannel implementation:
        // if (metadata.kind === 4) -> encrypts.
        // else -> kind 1, tags in metadata.tags.
        // So we need to pass tags manually for kind 1 mention.
        // Or we update NostrChannel to auto-tag if target is pubkey?
        // Let's pass tags explicitly.

        await alice.channelManager.sendMessage('nostr', 'dummy_target', 'Hello Bob', {
            kind: 1,
            tags: [['p', bobPub]]
        });

        const msgFromAlice = await bobReceived;
        expect(msgFromAlice.content).toBe('Hello Bob');
        expect(msgFromAlice.from).toBe(alicePub);

        // 2. Bob replies to Alice
        await bob.channelManager.sendMessage('nostr', 'dummy_target', 'Hello Alice', {
            kind: 1,
            tags: [['p', alicePub]]
        });

        const msgFromBob = await aliceReceived;
        expect(msgFromBob.content).toBe('Hello Alice');
        expect(msgFromBob.from).toBe(bobPub);
    });
});
